name: NS Alarm Postponer

on:
  schedule:
  - cron: "50 6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Activate virtual environment
      run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
      
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: setup python
      uses: actions/setup-python@v5
    
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run script
      run: |
        python api_connect.py
